<?php
$subtotal=0;foreach($products as $p){$price=(float)$p['sale_price']>0?(float)$p['sale_price']:(float)$p['price'];$subtotal+=$price*(int)$_SESSION['cart'][$p['id']];}
$shipping=($customer['shipping_method']??'DOMICILIO')==='RETIRO'?0:25;$total=$subtotal+$shipping;
?>
<div class="checkout-steps"><span class="done">1 Carrito</span><span class="done">2 Entrega</span><span class="active">3 Pago</span><span>4 Confirmación</span></div>
<div class="row g-4">
 <div class="col-xl-7">
  <div class="card p-4 p-md-5 payment-card">
   <div class="secure-title"><div><span class="eyebrow">PAGO SEGURO</span><h2 class="section mb-1">Tarjeta de crédito o débito</h2><p class="text-muted mb-0">Completa los datos para confirmar tu compra.</p></div><div class="secure-badge">🔒 Seguro</div></div>
   <form method="post" action="/?r=processPayment" id="paymentForm" autocomplete="off" novalidate>
    <input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="card_last4" id="card_last4"><input type="hidden" name="card_brand" id="card_brand">
    <div class="payment-visual"><div class="chip"></div><div class="visual-number" id="visualNumber">•••• •••• •••• ••••</div><div class="visual-bottom"><span id="visualName">NOMBRE DEL TITULAR</span><span id="visualExpiry">MM/AA</span></div></div>
    <label for="cardNumber">Número de tarjeta</label><div class="input-icon"><span>▣</span><input id="cardNumber" class="form-control" inputmode="numeric" maxlength="23" placeholder="0000 0000 0000 0000" required></div><div class="invalid-msg" id="numberError"></div>
    <div class="row g-3"><div class="col-md-6"><label for="expiry">Vencimiento</label><input id="expiry" class="form-control" inputmode="numeric" maxlength="5" placeholder="MM/AA" required><div class="invalid-msg" id="expiryError"></div></div><div class="col-md-6"><label for="cvv">Código de seguridad</label><input id="cvv" class="form-control" inputmode="numeric" maxlength="4" placeholder="CVV" required><div class="invalid-msg" id="cvvError"></div></div></div>
    <label for="holder">Nombre del titular</label><input id="holder" class="form-control" maxlength="80" placeholder="Como aparece en la tarjeta" required><div class="invalid-msg" id="holderError"></div>
    <button class="btn grad w-100 mt-4 py-3" id="payButton">Pagar Q<?=number_format($total,2)?></button>
    <div class="payment-note">Tus datos sensibles de tarjeta no se almacenan en MiMarket.</div>
   </form>
  </div>
 </div>
 <div class="col-xl-5"><div class="card p-4 summary sticky-summary"><h4>Resumen del pedido</h4><?php foreach($products as $p):$price=(float)$p['sale_price']>0?$p['sale_price']:$p['price'];?><div class="sumrow"><span><?=e($p['name'])?> × <?=(int)$_SESSION['cart'][$p['id']]?></span><b>Q<?=number_format($price*$_SESSION['cart'][$p['id']],2)?></b></div><?php endforeach;?><hr><div class="sumrow"><span>Subtotal</span><b>Q<?=number_format($subtotal,2)?></b></div><div class="sumrow"><span>Envío</span><b><?=$shipping?'Q'.number_format($shipping,2):'Sin costo'?></b></div><div class="sumrow total"><span>Total</span><b>Q<?=number_format($total,2)?></b></div><div class="deliverybox"><b><?=($customer['shipping_method']??'')==='RETIRO'?'Retiro en punto de entrega':'Entrega a domicilio'?></b><small class="d-block text-muted mt-1"><?=e($customer['address'])?></small></div></div></div>
</div>
<script>
(()=>{const form=document.getElementById('paymentForm'),num=document.getElementById('cardNumber'),exp=document.getElementById('expiry'),cvv=document.getElementById('cvv'),holder=document.getElementById('holder');const digits=v=>v.replace(/\D/g,'');function brand(n){if(/^4/.test(n))return 'Visa';if(/^5[1-5]/.test(n)||/^2(2[2-9]|[3-6]|7[01])/.test(n))return 'Mastercard';if(/^3[47]/.test(n))return 'American Express';return 'Tarjeta';}num.addEventListener('input',()=>{let d=digits(num.value).slice(0,19);num.value=d.replace(/(.{4})/g,'$1 ').trim();document.getElementById('visualNumber').textContent=num.value||'•••• •••• •••• ••••';});exp.addEventListener('input',()=>{let d=digits(exp.value).slice(0,4);exp.value=d.length>2?d.slice(0,2)+'/'+d.slice(2):d;document.getElementById('visualExpiry').textContent=exp.value||'MM/AA';});cvv.addEventListener('input',()=>cvv.value=digits(cvv.value).slice(0,4));holder.addEventListener('input',()=>document.getElementById('visualName').textContent=holder.value.toUpperCase()||'NOMBRE DEL TITULAR');form.addEventListener('submit',e=>{document.querySelectorAll('.invalid-msg').forEach(x=>x.textContent='');let ok=true,d=digits(num.value),m=Number(exp.value.slice(0,2)),y=Number(exp.value.slice(3,5));if(d.length<13||d.length>19){document.getElementById('numberError').textContent='Ingresa un número de tarjeta válido.';ok=false;}if(!/^\d{2}\/\d{2}$/.test(exp.value)||m<1||m>12||y<26){document.getElementById('expiryError').textContent='Revisa la fecha de vencimiento.';ok=false;}if(!/^\d{3,4}$/.test(cvv.value)){document.getElementById('cvvError').textContent='Revisa el código de seguridad.';ok=false;}if(holder.value.trim().length<4){document.getElementById('holderError').textContent='Ingresa el nombre del titular.';ok=false;}if(!ok){e.preventDefault();return;}document.getElementById('card_last4').value=d.slice(-4);document.getElementById('card_brand').value=brand(d);num.removeAttribute('name');exp.removeAttribute('name');cvv.removeAttribute('name');holder.removeAttribute('name');document.getElementById('payButton').disabled=true;document.getElementById('payButton').textContent='Procesando pago...';});})();
</script>
