<?php
/** Controlador principal: cada acción valida acceso y delega datos al modelo. */
class AppController {
 static function catalog(){$p=paginateArray(Store::products($_GET['search']??'',$_GET['category']??'',$_GET['brand']??'',$_GET['min']??'',$_GET['max']??'',$_GET['sort']??'new'));view('catalog/index',['products'=>$p['rows'],'pager'=>$p,'categories'=>Store::categories(),'brands'=>Store::brands()]);}
 static function product(){$p=Store::product((int)($_GET['id']??0));if(!$p){http_response_code(404);die('Producto no encontrado');}view('catalog/detail',['p'=>$p]);}
 static function login(){if(auth())redirect('/');view('auth/login');}
 static function doLogin(){checkCsrf();$key='login_'.clientIp();$a=$_SESSION[$key]??['n'=>0,'t'=>time()];if(time()-$a['t']<300&&$a['n']>=8){flash('Demasiados intentos. Espera unos minutos.');redirect('/?r=login');}$s=DB::get()->prepare("SELECT * FROM users WHERE email=? AND status='activo'");$s->execute([trim($_POST['email']??'')]);$u=$s->fetch();if($u&&password_verify($_POST['password']??'',$u['password'])){session_regenerate_id(true);unset($u['password'],$_SESSION[$key]);$_SESSION['user']=$u;$_SESSION['last_activity']=time();redirect('/');}$a['n']++;if(time()-$a['t']>=300)$a=['n'=>1,'t'=>time()];$_SESSION[$key]=$a;flash('Correo o contraseña incorrectos.');redirect('/?r=login');}
 static function register(){view('auth/register');}
 static function doRegister(){checkCsrf();$n=trim($_POST['name']??'');$em=trim($_POST['email']??'');$pw=$_POST['password']??'';if(strlen($n)<3||!filter_var($em,FILTER_VALIDATE_EMAIL)||!passwordStrong($pw)){flash('Usa un nombre válido y una contraseña de 8+ caracteres con letras y números.');redirect('/?r=register');}try{DB::get()->prepare("INSERT INTO users(name,email,password,role,status) VALUES(?,?,?,'cliente','activo')")->execute([$n,$em,password_hash($pw,PASSWORD_DEFAULT)]);flash('Cuenta creada. Ya puedes iniciar sesión.');redirect('/?r=login');}catch(Throwable $e){flash('Ese correo ya está registrado.');redirect('/?r=register');}}
 static function logout(){checkCsrf();$_SESSION=[];if(ini_get('session.use_cookies')){$p=session_get_cookie_params();setcookie(session_name(),'',time()-42000,$p['path'],$p['domain'],$p['secure'],$p['httponly']);}session_destroy();redirect('/?r=login');}
 static function forgot(){view('auth/forgot');}
 static function forgotSend(){checkCsrf();$email=trim($_POST['email']??'');$r=filter_var($email,FILTER_VALIDATE_EMAIL)?Store::createResetToken($email):null;if($r){$html='<h2>Recuperación MiMarket</h2><p>Tu código temporal es:</p><h1 style="color:#7c3aed;letter-spacing:5px">'.e($r['token']).'</h1><p>Expira en 15 minutos y solo puede utilizarse una vez.</p>';sendMailSMTP($email,'Código para cambiar tu contraseña - MiMarket',$html);}flash('Si el correo está registrado, recibirás un código temporal.');redirect('/?r=reset&email='.urlencode($email));}
 static function reset(){view('auth/reset',['email'=>$_GET['email']??'']);}
 static function resetSave(){checkCsrf();try{Store::resetPassword($_POST['email']??'',$_POST['token']??'',$_POST['password']??'');flash('Contraseña actualizada. Ya puedes iniciar sesión.');redirect('/?r=login');}catch(Throwable $e){flash($e->getMessage());redirect('/?r=reset&email='.urlencode($_POST['email']??''));}}
 static function profile(){requireAuth();view('account/profile',['u'=>Store::userById(auth()['id'])]);}
 static function profileSave(){requireAuth();checkCsrf();try{Store::updateProfile(auth()['id'],$_POST['name']??'',$_POST['email']??'',$_POST['current_password']??'',$_POST['new_password']??'');$u=Store::userById(auth()['id']);$_SESSION['user']=array_merge($_SESSION['user'],$u);flash('Perfil actualizado correctamente.');}catch(Throwable $e){flash($e->getMessage());}redirect('/?r=profile');}
 static function cart(){view('cart/index',['products'=>Store::cartProducts($_SESSION['cart']??[])]);}
 static function add(){checkCsrf();$id=(int)($_POST['id']??0);$p=Store::product($id);$q=max(1,(int)($_POST['qty']??1));if($p&&$p['status']==='activo'&&(int)$p['stock']>0)$_SESSION['cart'][$id]=min((int)$p['stock'],($_SESSION['cart'][$id]??0)+$q);redirect('/?r=cart');}
 static function remove(){checkCsrf();unset($_SESSION['cart'][(int)($_POST['id']??0)]);redirect('/?r=cart');}
 static function cartUpdate(){checkCsrf();$id=(int)($_POST['id']??0);$p=Store::product($id);$q=max(0,min((int)($_POST['qty']??0),(int)($p['stock']??0)));if($q)$_SESSION['cart'][$id]=$q;else unset($_SESSION['cart'][$id]);$products=Store::cartProducts($_SESSION['cart']??[]);$total=0;$sub=0;foreach($products as $x){$price=(float)$x['sale_price']>0?(float)$x['sale_price']:(float)$x['price'];$v=$price*(int)($_SESSION['cart'][$x['id']]??0);$total+=$v;if((int)$x['id']===$id)$sub=$v;}header('Content-Type: application/json');echo json_encode(['ok'=>true,'qty'=>$q,'subtotal'=>$sub,'total'=>$total,'count'=>array_sum($_SESSION['cart']??[])]);}
 static function checkout(){requireAuth();$products=Store::cartProducts($_SESSION['cart']??[]);if(!$products)redirect('/?r=cart');view('checkout/index',['products'=>$products]);}
 static function checkoutSave(){requireAuth();checkCsrf();$fullname=trim($_POST['fullname']??'');$email=trim($_POST['email']??'');$address=trim($_POST['address']??'');$shipping=in_array($_POST['shipping_method']??'',['DOMICILIO','RETIRO'],true)?$_POST['shipping_method']:'DOMICILIO';if(strlen($fullname)<3||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($address)<8){flash('Completa correctamente los datos de entrega.');redirect('/?r=checkout');}$_SESSION['checkout_customer']=['fullname'=>$fullname,'email'=>$email,'address'=>$address,'shipping_method'=>$shipping,'notes'=>trim($_POST['notes']??'')];redirect('/?r=pay');}
 static function pay(){requireAuth();if(empty($_SESSION['checkout_customer']))redirect('/?r=checkout');$products=Store::cartProducts($_SESSION['cart']??[]);if(!$products)redirect('/?r=cart');view('checkout/pay',['products'=>$products,'customer'=>$_SESSION['checkout_customer']]);}
 static function processPayment(){requireAuth();checkCsrf();$last4=preg_replace('/\D/','',$_POST['card_last4']??'');$brand=trim($_POST['card_brand']??'Tarjeta');if(!preg_match('/^\d{4}$/',$last4)){flash('No se pudo validar la información de pago.');redirect('/?r=pay');}try{$oid=Store::createOrder(auth()['id'],$_SESSION['checkout_customer']??[],$_SESSION['cart']??[],['brand'=>substr($brand,0,30),'last4'=>$last4]);$_SESSION['cart']=[];unset($_SESSION['checkout_customer']);$o=Store::orderDetail($oid);$pdf=invoicePdf($o);sendMailSMTP($o['email'],'Factura MiMarket - Pedido #'.$oid,'<h2>Gracias por tu compra</h2><p>Adjuntamos tu factura del pedido #'.$oid.'.</p>',$pdf,'Factura_MiMarket_'.$oid.'.pdf');flash('Pago aprobado. Tu factura está disponible y fue enviada al correo configurado.');redirect('/?r=orderDetail&id='.$oid);}catch(Throwable $e){flash($e->getMessage());redirect('/?r=cart');}}
 static function orders(){requireAuth();$p=paginateArray(Store::filteredOrders(staff()?null:auth()['id'],$_GET['q']??'',$_GET['status']??''));view('orders/index',['orders'=>$p['rows'],'pager'=>$p]);}
 static function orderDetail(){requireAuth();$o=Store::orderDetail((int)($_GET['id']??0));if(!$o||(!staff()&&(int)$o['user_id']!==(int)auth()['id'])){http_response_code(403);die('Pedido no disponible');}view('orders/detail',['o'=>$o]);}
 static function invoice(){requireAuth();$o=Store::orderDetail((int)($_GET['id']??0));if(!$o||(!staff()&&(int)$o['user_id']!==(int)auth()['id'])){http_response_code(403);die('Pedido no disponible');}$pdf=invoicePdf($o);header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="Factura_MiMarket_'.$o['id'].'.pdf"');echo $pdf;}
 static function admin(){requireStaff();view('admin/dashboard',['stats'=>Store::report(),'low'=>Store::lowStock(),'states'=>Store::reportStates(),'top'=>Store::topProducts()]);}
 static function adminProducts(){requireStaff();$p=paginateArray(Store::filteredProductsAdmin($_GET['q']??'',$_GET['status']??'',$_GET['category']??''));view('admin/products',['products'=>$p['rows'],'pager'=>$p,'categories'=>Store::categories()]);}
 static function productForm(){requireStaff();$p=!empty($_GET['id'])?Store::product((int)$_GET['id']):null;view('admin/product_form',['p'=>$p,'categories'=>Store::categories()]);}
 static function productSave(){requireStaff();checkCsrf();try{if(!empty($_FILES['image_file']['name'])){$f=$_FILES['image_file'];if($f['error']!==UPLOAD_ERR_OK)throw new Exception('No se pudo cargar la imagen.');if($f['size']>5*1024*1024)throw new Exception('La imagen supera 5 MB.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$mime]??null;if(!$ext)throw new Exception('Formato de imagen no permitido.');$name='product_'.bin2hex(random_bytes(6)).'.'.$ext;$dest=__DIR__.'/../../public/uploads/'.$name;if(!move_uploaded_file($f['tmp_name'],$dest))throw new Exception('No se pudo guardar la imagen.');$_POST['image']='uploads/'.$name;}else $_POST['image']=$_POST['existing_image']??'uploads/images.jpg';Store::saveProduct($_POST);flash('Producto guardado correctamente.');}catch(Throwable $e){flash('No se pudo guardar: '.$e->getMessage());}redirect('/?r=adminProducts');}
 static function categories(){requireStaff();$rows=Store::allCategories();$q=trim($_GET['q']??'');if($q!=='')$rows=array_values(array_filter($rows,fn($x)=>stripos($x['name'],$q)!==false));$p=paginateArray($rows);view('admin/categories',['categories'=>$p['rows'],'pager'=>$p]);}
 static function categorySave(){requireStaff();checkCsrf();try{Store::saveCategory((int)($_POST['id']??0),$_POST['name']??'',$_POST['status']??'activo');flash('Categoría guardada correctamente.');}catch(Throwable $e){flash('No se pudo guardar: '.$e->getMessage());}redirect('/?r=categories');}
 static function inventory(){requireStaff();$p=paginateArray(Store::filteredMovements($_GET['q']??'',$_GET['type']??''));view('admin/inventory',['products'=>Store::allProducts(),'movements'=>$p['rows'],'pager'=>$p,'low'=>Store::lowStock()]);}
 static function stockAdjust(){requireStaff();checkCsrf();try{Store::adjustStock((int)($_POST['product_id']??0),max(1,(int)($_POST['quantity']??1)),$_POST['type']??'ENTRADA',trim($_POST['reason']??'Ajuste manual'));flash('Existencia actualizada.');}catch(Throwable $e){flash($e->getMessage());}redirect('/?r=inventory');}
 static function adminOrders(){requireStaff();$p=paginateArray(Store::filteredOrders(null,$_GET['q']??'',$_GET['status']??''));view('admin/orders',['orders'=>$p['rows'],'pager'=>$p]);}
 static function status(){requireStaff();checkCsrf();try{Store::setStatus((int)($_POST['id']??0),$_POST['status']??'');flash('Estado actualizado.');}catch(Throwable $e){flash($e->getMessage());}redirect('/?r=adminOrders');}
 static function reports(){requireStaff();$rows=Store::analyticsOrders($_GET['from']??'',$_GET['to']??'',$_GET['status']??'',$_GET['payment']??'',$_GET['shipping']??'',$_GET['q']??'');$p=paginateArray($rows);view('admin/reports',['stats'=>Store::analyticsSummary($rows),'states'=>Store::reportStates($_GET['from']??'',$_GET['to']??''),'top'=>Store::topProducts($_GET['from']??'',$_GET['to']??''),'low'=>Store::lowStock(),'orders'=>$p['rows'],'pager'=>$p]);}
 static function users(){requireAdmin();$p=paginateArray(Store::filteredUsers($_GET['q']??'',$_GET['role']??'',$_GET['status']??''));view('admin/users',['users'=>$p['rows'],'pager'=>$p]);}
 static function userRole(){requireAdmin();checkCsrf();try{Store::setUser((int)($_POST['id']??0),$_POST['role']??'cliente',$_POST['status']??'activo');flash('Usuario actualizado.');}catch(Throwable $e){flash($e->getMessage());}redirect('/?r=users');}
 static function exportReport(){requireStaff();$rows=Store::analyticsOrders($_GET['from']??'',$_GET['to']??'',$_GET['status']??'',$_GET['payment']??'',$_GET['shipping']??'',$_GET['q']??'');$stats=Store::analyticsSummary($rows);$data=[];foreach($rows as $o)$data[]=['#'.$o['id'],$o['created_at'],$o['fullname'],$o['status'],$o['payment_status'],'Q'.number_format($o['total'],2)];if(($_GET['type']??'pdf')==='excel')return self::excelOut('Reporte_Analitico',['Pedido','Fecha','Cliente','Estado','Pago','Total'],$data);$pdf=pdfTableDocument('REPORTE ANALÍTICO','Filtros aplicados desde el módulo de reportería',['Pedido','Fecha','Cliente','Estado','Pago','Total'],$data,['Ventas'=>'Q'.number_format($stats['sales'],2),'Pedidos'=>$stats['orders_count'],'Ticket prom.'=>'Q'.number_format($stats['avg_sale'],2),'Entregados'=>$stats['delivered']]);self::pdfOut('Reporte_Analitico',$pdf);}
 static function exportModule(){requireStaff();$m=$_GET['module']??'';$headers=[];$data=[];$title='Reporte';switch($m){case'products':$title='Productos';$headers=['ID','SKU','Producto','Marca','Categoría','Unidad','Precio','Stock','Estado'];foreach(Store::filteredProductsAdmin($_GET['q']??'',$_GET['status']??'',$_GET['category']??'') as $x)$data[]=[ $x['id'],$x['sku'],$x['name'],$x['brand'],$x['category'],$x['unit_type']??'unidad','Q'.number_format((float)$x['price'],2),$x['stock'],$x['status']];break;case'categories':$title='Categorías';$headers=['ID','Categoría','Estado'];foreach(Store::allCategories() as $x){if(($_GET['q']??'')===''||stripos($x['name'],$_GET['q'])!==false)$data[]=[$x['id'],$x['name'],$x['status']];}break;case'inventory':$title='Inventario';$headers=['Fecha','SKU','Producto','Tipo','Cantidad','Motivo','Usuario'];foreach(Store::filteredMovements($_GET['q']??'',$_GET['type']??'') as $x)$data[]=[$x['created_at'],$x['sku'],$x['product'],$x['type'],$x['quantity'],$x['reason'],$x['user_name']??'Sistema'];break;case'orders':$title='Pedidos';$headers=['Pedido','Fecha','Cliente','Correo','Estado','Pago','Total'];foreach(Store::filteredOrders(null,$_GET['q']??'',$_GET['status']??'') as $x)$data[]=['#'.$x['id'],$x['created_at'],$x['fullname'],$x['email'],$x['status'],$x['payment_status'],'Q'.number_format($x['total'],2)];break;case'users':requireAdmin();$title='Usuarios';$headers=['ID','Nombre','Correo','Rol','Estado','Creado'];foreach(Store::filteredUsers($_GET['q']??'',$_GET['role']??'',$_GET['status']??'') as $x)$data[]=[$x['id'],$x['name'],$x['email'],$x['role'],$x['status'],$x['created_at']];break;default:http_response_code(400);die('Módulo no válido');}if(($_GET['type']??'pdf')==='excel')return self::excelOut($title,$headers,$data);self::pdfOut($title,pdfTableDocument(strtoupper($title),'Exportación MiMarket con filtros aplicados',$headers,$data,['Registros'=>count($data),'Generado'=>date('d/m/Y H:i')]));}
 static function excelOut($name,$headers,$rows){header('Content-Type: application/vnd.ms-excel; charset=UTF-8');header('Content-Disposition: attachment; filename="MiMarket_'.$name.'_'.date('Ymd_His').'.xls"');echo "\xEF\xBB\xBF<table border=1><tr><th colspan=\"".count($headers)."\">MiMarket - ".e($name)."</th></tr><tr>";foreach($headers as $h)echo '<th>'.e($h).'</th>';echo '</tr>';foreach($rows as $r){echo '<tr>';foreach($r as $v)echo '<td>'.e($v).'</td>';echo '</tr>';}echo '</table>';exit;}
 static function pdfOut($name,$pdf){header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="MiMarket_'.$name.'_'.date('Ymd_His').'.pdf"');echo $pdf;exit;}
 static function health(){header('Content-Type: application/json');echo json_encode(['status'=>'ok','time'=>date(DATE_ATOM)]);}
}
