<?php
class Store {
 static function categories(){return DB::get()->query("SELECT * FROM categories WHERE status='activo' ORDER BY name")->fetchAll();}
 static function allCategories(){return DB::get()->query('SELECT * FROM categories ORDER BY name')->fetchAll();}
 static function saveCategory($id,$name,$status){$name=substr(trim($name),0,100);if($name==='')throw new Exception('El nombre de categoría es obligatorio.');$status=$status==='inactivo'?'inactivo':'activo';if((int)$id){DB::get()->prepare('UPDATE categories SET name=?,status=? WHERE id=?')->execute([$name,$status,(int)$id]);}else{DB::get()->prepare('INSERT INTO categories(name,status) VALUES(?,?)')->execute([$name,$status]);}}
 static function brands(){return DB::get()->query("SELECT DISTINCT brand FROM products WHERE brand<>'' AND status='activo' ORDER BY brand")->fetchAll(PDO::FETCH_COLUMN);}
 static function products($q='',$cat='',$brand='',$min='',$max='',$sort='new'){$sql="SELECT p.*,c.name category FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.status='activo'";$a=[];if($q!==''){$sql.=' AND (p.name LIKE ? OR p.description LIKE ? OR p.brand LIKE ? OR p.sku LIKE ?)';for($i=0;$i<4;$i++)$a[]="%$q%";}if($cat!==''){$sql.=' AND p.category_id=?';$a[]=(int)$cat;}if($brand!==''){$sql.=' AND p.brand=?';$a[]=$brand;}if($min!==''){$sql.=' AND COALESCE(NULLIF(p.sale_price,0),p.price)>=?';$a[]=(float)$min;}if($max!==''){$sql.=' AND COALESCE(NULLIF(p.sale_price,0),p.price)<=?';$a[]=(float)$max;}$orders=['price_asc'=>'COALESCE(NULLIF(p.sale_price,0),p.price) ASC','price_desc'=>'COALESCE(NULLIF(p.sale_price,0),p.price) DESC','name'=>'p.name ASC','new'=>'p.id DESC'];$sql.=' ORDER BY '.($orders[$sort]??$orders['new']);$s=DB::get()->prepare($sql);$s->execute($a);return $s->fetchAll();}
 static function allProducts(){return DB::get()->query('SELECT p.*,c.name category FROM products p LEFT JOIN categories c ON c.id=p.category_id ORDER BY p.id DESC')->fetchAll();}
 static function product($id){$s=DB::get()->prepare('SELECT p.*,c.name category FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.id=?');$s->execute([(int)$id]);return $s->fetch();}
 static function cartProducts($cart){if(!$cart)return [];$ids=array_map('intval',array_keys($cart));$ph=implode(',',array_fill(0,count($ids),'?'));$s=DB::get()->prepare("SELECT * FROM products WHERE id IN ($ph) AND status='activo'");$s->execute($ids);return $s->fetchAll();}
 static function saveProduct($d){$db=DB::get();$id=(int)($d['id']??0);$sku=substr(strtoupper(trim($d['sku']??'')),0,30);$name=substr(trim($d['name']??''),0,120);if($sku===''||$name==='')throw new Exception('SKU y nombre son obligatorios.');$unit=in_array($d['unit_type']??'unidad',['unidad','lb','kg','paquete','caja','litro','metro'],true)?$d['unit_type']:'unidad';$vals=[$sku,$name,substr(trim($d['brand']??''),0,80),substr(trim($d['description']??''),0,1000),max(0,(float)($d['price']??0)),max(0,(float)($d['sale_price']??0)),$unit,max(0,(int)($d['stock']??0)),max(0,(int)($d['min_stock']??0)),(int)($d['category_id']??0),trim($d['image']??'')?:'uploads/images.jpg',($d['status']??'activo')==='inactivo'?'inactivo':'activo'];if($id){$old=self::product($id);$vals[]=$id;$db->prepare('UPDATE products SET sku=?,name=?,brand=?,description=?,price=?,sale_price=?,unit_type=?,stock=?,min_stock=?,category_id=?,image=?,status=? WHERE id=?')->execute($vals);if($old&&(int)$old['stock']!==(int)($d['stock']??0))self::movement($id,(int)($d['stock']??0)-(int)$old['stock'],'AJUSTE','Edición de producto',auth()['id']??null);return $id;}$db->prepare('INSERT INTO products(sku,name,brand,description,price,sale_price,unit_type,stock,min_stock,category_id,image,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)')->execute($vals);$id=(int)$db->lastInsertId();if((int)($d['stock']??0)>0)self::movement($id,(int)$d['stock'],'ENTRADA','Stock inicial',auth()['id']??null);return $id;}
 static function adjustStock($id,$qty,$type,$reason){$db=DB::get();$p=self::product($id);if(!$p)throw new Exception('Producto no encontrado.');$type=in_array($type,['ENTRADA','SALIDA','AJUSTE'],true)?$type:'AJUSTE';$delta=$type==='SALIDA'?-abs((int)$qty):abs((int)$qty);if((int)$p['stock']+$delta<0)throw new Exception('La salida supera el stock disponible.');$db->prepare('UPDATE products SET stock=stock+? WHERE id=?')->execute([$delta,(int)$id]);self::movement($id,$delta,$type,$reason,auth()['id']??null);}
 static function movement($pid,$qty,$type,$reason,$uid){DB::get()->prepare('INSERT INTO inventory_movements(product_id,quantity,type,reason,user_id) VALUES(?,?,?,?,?)')->execute([(int)$pid,(int)$qty,$type,$reason,$uid]);}
 static function movements(){return DB::get()->query('SELECT m.*,p.name product,p.sku,u.name user_name FROM inventory_movements m JOIN products p ON p.id=m.product_id LEFT JOIN users u ON u.id=m.user_id ORDER BY m.id DESC LIMIT 150')->fetchAll();}
 static function createOrder($uid,$customer,$cart,$payment){$db=DB::get();$db->beginTransaction();try{$ids=array_map('intval',array_keys($cart));if(!$ids)throw new Exception('El carrito está vacío.');$ph=implode(',',array_fill(0,count($ids),'?'));$s=$db->prepare("SELECT * FROM products WHERE id IN ($ph) AND status='activo' FOR UPDATE");$s->execute($ids);$items=$s->fetchAll();if(count($items)!==count($ids))throw new Exception('Uno de los productos ya no está disponible.');$subtotal=0;foreach($items as $x){$q=(int)($cart[$x['id']]??0);if($q<1||$q>(int)$x['stock'])throw new Exception('Stock insuficiente para '.$x['name'].'.');$price=(float)$x['sale_price']>0?(float)$x['sale_price']:(float)$x['price'];$subtotal+=$price*$q;}$shipping=($customer['shipping_method']??'DOMICILIO')==='RETIRO'?0.00:25.00;$total=$subtotal+$shipping;$ref='MM-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$s=$db->prepare("INSERT INTO orders(user_id,fullname,email,address,subtotal,shipping_cost,total,status,payment_method,payment_status,payment_reference,card_brand,card_last4,shipping_method,notes) VALUES(?,?,?,?,?,?,?,'PEDIDO','TARJETA','PAGADO',?,?,?,?,?)");$s->execute([(int)$uid,$customer['fullname'],$customer['email'],$customer['address'],$subtotal,$shipping,$total,$ref,$payment['brand'],$payment['last4'],$customer['shipping_method']??'DOMICILIO',$customer['notes']??'']);$oid=(int)$db->lastInsertId();foreach($items as $x){$q=(int)$cart[$x['id']];$price=(float)$x['sale_price']>0?(float)$x['sale_price']:(float)$x['price'];$db->prepare('INSERT INTO order_items(order_id,product_id,quantity,unit_price,subtotal) VALUES(?,?,?,?,?)')->execute([$oid,$x['id'],$q,$price,$price*$q]);$db->prepare('UPDATE products SET stock=stock-? WHERE id=?')->execute([$q,$x['id']]);self::movement($x['id'],-$q,'VENTA','Pedido #'.$oid,$uid);}$db->prepare("INSERT INTO order_status_history(order_id,status,changed_by,notes) VALUES(?,'PEDIDO',?,?)")->execute([$oid,$uid,'Pedido recibido']);$db->commit();return $oid;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
 static function orders($uid=null){$sql='SELECT o.*,u.name user_name FROM orders o LEFT JOIN users u ON u.id=o.user_id';$a=[];if($uid){$sql.=' WHERE o.user_id=?';$a[]=(int)$uid;}$sql.=' ORDER BY o.id DESC';$s=DB::get()->prepare($sql);$s->execute($a);return $s->fetchAll();}
 static function orderDetail($id){$s=DB::get()->prepare('SELECT o.*,u.name user_name FROM orders o LEFT JOIN users u ON u.id=o.user_id WHERE o.id=?');$s->execute([(int)$id]);$o=$s->fetch();if(!$o)return null;$s=DB::get()->prepare('SELECT i.*,p.name,p.image,p.sku FROM order_items i JOIN products p ON p.id=i.product_id WHERE i.order_id=?');$s->execute([(int)$id]);$o['items']=$s->fetchAll();$s=DB::get()->prepare('SELECT h.*,u.name changed_name FROM order_status_history h LEFT JOIN users u ON u.id=h.changed_by WHERE h.order_id=? ORDER BY h.id');$s->execute([(int)$id]);$o['history']=$s->fetchAll();return $o;}
 static function setStatus($id,$status){
  $steps=['PEDIDO','PREPARACION','LISTO','EN_CAMINO','ENTREGADO'];
  $allowed=array_merge($steps,['CANCELADO']);
  if(!in_array($status,$allowed,true))throw new Exception('Estado no válido.');
  $db=DB::get();
  $s=$db->prepare('SELECT status FROM orders WHERE id=?');$s->execute([(int)$id]);$current=$s->fetchColumn();
  if(!$current)throw new Exception('Pedido no encontrado.');
  if($current===$status)throw new Exception('Ese estado ya fue registrado.');
  if(in_array($current,['ENTREGADO','CANCELADO'],true))throw new Exception('Este pedido ya tiene un estado final.');
  if($status==='CANCELADO'){
    $db->beginTransaction();
    try{
      $db->prepare('UPDATE orders SET status=? WHERE id=?')->execute([$status,(int)$id]);
      $exists=$db->prepare('SELECT 1 FROM order_status_history WHERE order_id=? AND status=? LIMIT 1');$exists->execute([(int)$id,$status]);
      if(!$exists->fetchColumn())$db->prepare('INSERT INTO order_status_history(order_id,status,changed_by,notes) VALUES(?,?,?,?)')->execute([(int)$id,$status,auth()['id']??null,'Pedido cancelado']);
      $db->commit(); return true;
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
  }
  $curPos=array_search($current,$steps,true);$newPos=array_search($status,$steps,true);
  if($curPos===false||$newPos===false||$newPos<$curPos)throw new Exception('No puedes retroceder el estado del pedido.');
  $db->beginTransaction();
  try{
    $db->prepare('UPDATE orders SET status=? WHERE id=?')->execute([$status,(int)$id]);
    $exists=$db->prepare('SELECT 1 FROM order_status_history WHERE order_id=? AND status=? LIMIT 1');
    for($i=$curPos+1;$i<=$newPos;$i++){
      $step=$steps[$i];$exists->execute([(int)$id,$step]);
      if(!$exists->fetchColumn())$db->prepare('INSERT INTO order_status_history(order_id,status,changed_by,notes) VALUES(?,?,?,?)')->execute([(int)$id,$step,auth()['id']??null,'Actualización de estado']);
    }
    $db->commit();return true;
  }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
 }
 static function report($from='',$to=''){ $sql="SELECT COUNT(*) orders_count,COALESCE(SUM(total),0) sales,COALESCE(AVG(total),0) avg_sale,COALESCE(SUM(status='ENTREGADO'),0) delivered FROM orders WHERE payment_status='PAGADO'";$a=[];if($from!==''){$sql.=' AND created_at>=?';$a[]=$from.' 00:00:00';}if($to!==''){$sql.=' AND created_at<=?';$a[]=$to.' 23:59:59';}$q=DB::get()->prepare($sql);$q->execute($a);return $q->fetch();}
 static function reportStates($from='',$to=''){ $sql='SELECT status,COUNT(*) qty FROM orders WHERE 1=1';$a=[];if($from!==''){$sql.=' AND created_at>=?';$a[]=$from.' 00:00:00';}if($to!==''){$sql.=' AND created_at<=?';$a[]=$to.' 23:59:59';}$sql.=' GROUP BY status ORDER BY qty DESC';$q=DB::get()->prepare($sql);$q->execute($a);return $q->fetchAll();}
 static function topProducts($from='',$to=''){ $sql='SELECT p.name,SUM(i.quantity) qty,SUM(i.subtotal) sales FROM order_items i JOIN products p ON p.id=i.product_id JOIN orders o ON o.id=i.order_id WHERE 1=1';$a=[];if($from!==''){$sql.=' AND DATE(o.created_at)>=?';$a[]=$from;}if($to!==''){$sql.=' AND DATE(o.created_at)<=?';$a[]=$to;}$sql.=' GROUP BY p.id,p.name ORDER BY qty DESC LIMIT 10';$q=DB::get()->prepare($sql);$q->execute($a);return $q->fetchAll();}
 static function lowStock(){return DB::get()->query("SELECT * FROM products WHERE stock<=min_stock AND status='activo' ORDER BY stock ASC")->fetchAll();}
 static function users(){return DB::get()->query('SELECT id,name,email,role,status,created_at FROM users ORDER BY id DESC')->fetchAll();}
 static function setUser($id,$role,$status){if(!in_array($role,['cliente','operador','admin'],true))throw new Exception('Rol no válido.');if(!in_array($status,['activo','inactivo'],true))throw new Exception('Estado no válido.');if((int)$id===(int)(auth()['id']??0)&&$status==='inactivo')throw new Exception('No puedes desactivar tu propia cuenta.');return DB::get()->prepare('UPDATE users SET role=?,status=? WHERE id=?')->execute([$role,$status,(int)$id]);}

 static function filteredProductsAdmin($q='',$status='',$cat=''){ $sql='SELECT p.*,c.name category FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE 1=1';$a=[];if($q!==''){$sql.=' AND (p.name LIKE ? OR p.sku LIKE ? OR p.brand LIKE ?)';$a=array_fill(0,3,"%$q%");}if(in_array($status,['activo','inactivo'],true)){$sql.=' AND p.status=?';$a[]=$status;}if($cat!==''){$sql.=' AND p.category_id=?';$a[]=(int)$cat;}$sql.=' ORDER BY p.id DESC';$s=DB::get()->prepare($sql);$s->execute($a);return $s->fetchAll();}
 static function filteredUsers($q='',$role='',$status=''){ $sql='SELECT id,name,email,role,status,created_at FROM users WHERE 1=1';$a=[];if($q!==''){$sql.=' AND (name LIKE ? OR email LIKE ?)';$a=["%$q%","%$q%"];}if(in_array($role,['cliente','operador','admin'],true)){$sql.=' AND role=?';$a[]=$role;}if(in_array($status,['activo','inactivo'],true)){$sql.=' AND status=?';$a[]=$status;}$sql.=' ORDER BY id DESC';$s=DB::get()->prepare($sql);$s->execute($a);return $s->fetchAll();}
 static function filteredOrders($uid=null,$q='',$status=''){ $sql='SELECT o.*,u.name user_name FROM orders o LEFT JOIN users u ON u.id=o.user_id WHERE 1=1';$a=[];if($uid){$sql.=' AND o.user_id=?';$a[]=(int)$uid;}if($q!==''){$sql.=' AND (o.fullname LIKE ? OR o.email LIKE ? OR CAST(o.id AS CHAR) LIKE ?)';$a[]="%$q%";$a[]="%$q%";$a[]="%$q%";}if(in_array($status,['PEDIDO','PREPARACION','LISTO','EN_CAMINO','ENTREGADO','CANCELADO'],true)){$sql.=' AND o.status=?';$a[]=$status;}$sql.=' ORDER BY o.id DESC';$s=DB::get()->prepare($sql);$s->execute($a);return $s->fetchAll();}
 static function filteredMovements($q='',$type=''){ $sql='SELECT m.*,p.name product,p.sku,u.name user_name FROM inventory_movements m JOIN products p ON p.id=m.product_id LEFT JOIN users u ON u.id=m.user_id WHERE 1=1';$a=[];if($q!==''){$sql.=' AND (p.name LIKE ? OR p.sku LIKE ? OR m.reason LIKE ?)';$a=array_fill(0,3,"%$q%");}if(in_array($type,['ENTRADA','SALIDA','VENTA','AJUSTE'],true)){$sql.=' AND m.type=?';$a[]=$type;}$sql.=' ORDER BY m.id DESC';$s=DB::get()->prepare($sql);$s->execute($a);return $s->fetchAll();}
 static function userById($id){$s=DB::get()->prepare('SELECT id,name,email,role,status,created_at FROM users WHERE id=?');$s->execute([(int)$id]);return $s->fetch();}
 static function updateProfile($id,$name,$email,$current,$new=''){ $db=DB::get();$s=$db->prepare('SELECT * FROM users WHERE id=?');$s->execute([(int)$id]);$u=$s->fetch();if(!$u||!password_verify($current,$u['password']))throw new Exception('La contraseña actual no es correcta.');if(strlen(trim($name))<3||!filter_var($email,FILTER_VALIDATE_EMAIL))throw new Exception('Nombre o correo no válido.');if($new!==''&&!passwordStrong($new))throw new Exception('La nueva contraseña debe tener al menos 8 caracteres, letras y números.');try{$sql='UPDATE users SET name=?,email=?'.($new!==''?',password=?':'').' WHERE id=?';$a=[trim($name),trim($email)];if($new!=='')$a[]=password_hash($new,PASSWORD_DEFAULT);$a[]=(int)$id;$db->prepare($sql)->execute($a);}catch(PDOException $e){throw new Exception('El correo ya está registrado.');}}
 static function createResetToken($email){$db=DB::get();$s=$db->prepare("SELECT id,email FROM users WHERE email=? AND status='activo'");$s->execute([trim($email)]);$u=$s->fetch();if(!$u)return null;$token=(string)random_int(100000,999999);$hash=hash('sha256',$token);$db->prepare('DELETE FROM password_resets WHERE user_id=?')->execute([$u['id']]);$db->prepare('INSERT INTO password_resets(user_id,token_hash,expires_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 15 MINUTE))')->execute([$u['id'],$hash]);return ['token'=>$token,'user'=>$u];}
 static function resetPassword($email,$token,$password){if(!passwordStrong($password))throw new Exception('La contraseña debe tener al menos 8 caracteres, letras y números.');$db=DB::get();$s=$db->prepare("SELECT pr.id,pr.user_id FROM password_resets pr JOIN users u ON u.id=pr.user_id WHERE u.email=? AND pr.token_hash=? AND pr.used_at IS NULL AND pr.expires_at>NOW() ORDER BY pr.id DESC LIMIT 1");$s->execute([trim($email),hash('sha256',trim($token))]);$r=$s->fetch();if(!$r)throw new Exception('El token es inválido o ya expiró.');$db->beginTransaction();$db->prepare('UPDATE users SET password=? WHERE id=?')->execute([password_hash($password,PASSWORD_DEFAULT),$r['user_id']]);$db->prepare('UPDATE password_resets SET used_at=NOW() WHERE id=?')->execute([$r['id']]);$db->commit();}
 static function analyticsOrders($from='',$to='',$status='',$payment='',$shipping='',$q=''){ $sql='SELECT o.*,u.name user_name FROM orders o LEFT JOIN users u ON u.id=o.user_id WHERE 1=1';$a=[];if($from!==''){$sql.=' AND DATE(o.created_at)>=?';$a[]=$from;}if($to!==''){$sql.=' AND DATE(o.created_at)<=?';$a[]=$to;}if($status!==''){$sql.=' AND o.status=?';$a[]=$status;}if($payment!==''){$sql.=' AND o.payment_status=?';$a[]=$payment;}if($shipping!==''){$sql.=' AND o.shipping_method=?';$a[]=$shipping;}if($q!==''){$sql.=' AND (o.fullname LIKE ? OR o.email LIKE ? OR CAST(o.id AS CHAR) LIKE ?)';$a=array_merge($a,["%$q%","%$q%","%$q%"]);}$sql.=' ORDER BY o.id DESC';$s=DB::get()->prepare($sql);$s->execute($a);return $s->fetchAll();}
 static function analyticsSummary($rows){$sales=0;$del=0;$cancel=0;foreach($rows as $o){if(($o['payment_status']??'')==='PAGADO')$sales+=(float)$o['total'];if($o['status']==='ENTREGADO')$del++;if($o['status']==='CANCELADO')$cancel++;}$n=count($rows);return ['sales'=>$sales,'orders_count'=>$n,'avg_sale'=>$n?$sales/$n:0,'delivered'=>$del,'cancelled'=>$cancel];}

}
